### ISSUE TITLE
【Bug】Index out of array bounds

### ISSUE THREAD

**Issue by AiKier** [station384/WowFishingAssist#2]
`
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 WowFishingAssist.MainForm.buStartStop_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4390.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WowFishingAssist
    程序集版本:0.5.5.0
    Win32 版本:0.5.0.0
    基本代码:file:///C:/Program%20Files/WowFishingAssist/WowFishingAssist.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4390.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4360.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.4390.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AForge.Vision
    程序集版本:2.2.5.0
    Win32 版本:2.2.5.0
    基本代码:file:///C:/Program%20Files/WowFishingAssist/AForge.Vision.DLL
----------------------------------------
AForge.Imaging
    程序集版本:2.2.5.0
    Win32 版本:2.2.5.0
    基本代码:file:///C:/Program%20Files/WowFishingAssist/AForge.Imaging.DLL
----------------------------------------
AForge
    程序集版本:2.2.5.0
    Win32 版本:2.2.5.0
    基本代码:file:///C:/Program%20Files/WowFishingAssist/AForge.DLL
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.4190.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4390.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SharpDX.Direct3D11
    程序集版本:4.2.0.0
    Win32 版本:4.2.0
    基本代码:file:///C:/Program%20Files/WowFishingAssist/SharpDX.Direct3D11.DLL
----------------------------------------
SharpDX.DXGI
    程序集版本:4.2.0.0
    Win32 版本:4.2.0
    基本代码:file:///C:/Program%20Files/WowFishingAssist/SharpDX.DXGI.DLL
----------------------------------------
SharpDX
    程序集版本:4.2.0.0
    Win32 版本:4.2.0
    基本代码:file:///C:/Program%20Files/WowFishingAssist/SharpDX.DLL
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

`

**Comment by station384** [comment]
I will look into this. 

Is there a procedure to reproduce the out of bounds error or is it random?

**Comment by AiKier** [comment]
From 5.1 to 5.5, it's the same on my laptop.
System Windows 10

**Comment by station384** [comment]
This is caused when start is clicked and the Wow.exe process has not been started.

I develop in English, so in the code I am looking for the **Wow** process, I do not know if this is the same in other languages.
In the meantime I am adding a check to the start that will display a warning if the wow process is not found.
[https://github.com/station384/WowFishingAssist/releases/tag/0.5.6](url)

**Comment by AiKier** [comment]
> This is caused when start is clicked and the Wow.exe process has not been started.
> 
> I develop in English, so in the code I am looking for the **Wow** process, I do not know if this is the same in other languages.
> In the meantime I am adding a check to the start that will display a warning if the wow process is not found.
> [https://github.com/station384/WowFishingAssist/releases/tag/0.5.6](url)

I'm sure I started wow.exe. Is it because I started wow classic?

**Comment by station384** [comment]
This may be the case.  

I have not tested it with wow classic.

When I get a little time I will check and see if the process name is different.

 

It should work fine in principle,  the junk selling won’t work as there isn’t a tundra mount, and a few other things like baits and what not won’t work as well,  but the main function should work fine.

**Comment by AiKier** [comment]
> This may be the case. I have not tested it with wow classic. When I get a little time I will check and see if the process name is different. It should work fine in principle, the junk selling won’t work as there isn’t a tundra mount, and a few other things like baits and what not won’t work as well, but the main function should work fine. 

Thank you. I'll try 0.5.6

**Comment by station384** [comment]
I have put in a check for wowclassic,  it should start and attempt to work in wow classic.   

Closing this out and adding separate issue to make this fully compatible with classic

#3

**Comment by AiKier** [comment]
Excuse me, what is the shortcut key for fishing?
